# Generated by Django 4.2.29 on 2026-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_smtpsettings_enable_password_reset_usersecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='host_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
