# Generated by Django 4.2.29 on 2026-04-22 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0006_smtpsettings_enable_registration_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.CharField(max_length=100)),
                ('exchange_segment', models.CharField(max_length=50)),
                ('trading_symbol', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('transaction_type', models.CharField(max_length=5)),
                ('product_type', models.CharField(max_length=50)),
                ('order_type', models.CharField(default='L', max_length=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basket Order',
                'verbose_name_plural': 'Basket Orders',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
