# Generated by Django 4.2.29 on 2026-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_basketorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_enabled', models.BooleanField(default=True, help_text='Enable automatic logoff after inactivity')),
                ('session_timeout_seconds', models.IntegerField(default=300, help_text='User session timeout in seconds (default 5 min)')),
                ('sdk_timeout_enabled', models.BooleanField(default=True, help_text='Enable mandatory SDK re-authentication after duration')),
                ('sdk_timeout_seconds', models.IntegerField(default=1800, help_text='SDK session timeout in seconds (default 30 min)')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
