# Generated by Django 4.2.29 on 2026-05-02 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0009_platformsettings_enable_user_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userneocredentials',
            name='sdk_session_active',
        ),
        migrations.RemoveField(
            model_name='userneocredentials',
            name='sdk_session_expires_at',
        ),
        migrations.RemoveField(
            model_name='userneocredentials',
            name='sdk_session_started_at',
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='sdk_session_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='sdk_session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='sdk_session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
