# Generated by Django 4.2.29 on 2026-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_remove_userneocredentials_sdk_session_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='allow_session_restore',
            field=models.BooleanField(default=False, help_text='Allow restoring user and SDK sessions after server restarts'),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='sdk_session_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
