"""
Django settings for trading_platform project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import uuid
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-v*580nj=cr4_q!@u(n+mopu-^(0tiy+n@z_9q@38mrede6j9#%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']

# Unique ID for the current server process to detect restarts
SERVER_BOOT_ID = str(uuid.uuid4())

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trades',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'trading_platform.middleware.RequestLoggingMiddleware',
    'trading_platform.middleware.RestartDetectionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'trades.auth_middleware.SessionExpiryMiddleware',
]

ROOT_URLCONF = 'trading_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trading_platform.wsgi.application'
ASGI_APPLICATION = 'trading_platform.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Kotak Neo Trade API credentials
# NOTE: Credentials are now managed through the database/UI and encrypted using ENCRYPTION_KEY from .env
KOTAK_NEO_API_CREDENTIALS = {
    'MPIN': 'MPIN_PLACEHOLDER',
    'TOTP_SECRET': 'TOTP_SECRET_PLACEHOLDER',
    'CONSUMER_KEY': 'CONSUMER_KEY_PLACEHOLDER',
    'CONSUMER_SECRET': 'CONSUMER_SECRET_PLACEHOLDER',
    'MOBILE_NUMBER': '+00000000000',
    'UCC': 'DEMO123',
    'ACCOUNT_NAME': 'Demo Account',
}

# Session Configuration - 5 minutes expiry on inactivity
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 300  # 5 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Reset timer on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Login URL
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'

import os
# Configure logging: asynchronous, full debug capture, prepended with UUIDs.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'trading_platform.logging_utils.RequestIDFilter',
        },
    },
    'formatters': {
        'multiline': {
            '()': 'trading_platform.logging_utils.MultiLineFormatter',
            'format': '%(asctime)s - %(levelname)s - [%(request_id)s|%(request_user)s] - %(message)s'
        },
    },
    'handlers': {
        'async_file': {
            'level': 'DEBUG',
            'class': 'trading_platform.logging_utils.SimpleAsyncFileHandler',
            'filename': os.path.join(BASE_DIR, 'app_activity.log'),
            'formatter': 'multiline',
            'filters': ['request_id'],
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'multiline',
            'filters': ['request_id'],
        }
    },
    'loggers': {
        # Catch-all root logger for everything
        '': {
            'handlers': ['async_file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['async_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}